<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>GlassM</AssemblyName>
    <RootNamespace>GlassM</RootNamespace>
    <Version>0.1.0</Version>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>C:\Users\Administrator\Desktop\work\Cu-SaveManager-main\references\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>C:\Users\Administrator\Desktop\work\Cu-SaveManager-main\references\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>C:\Users\Administrator\Desktop\work\Cu-SaveManager-main\references\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>C:\Users\Administrator\Desktop\work\Cu-SaveManager-main\references\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>C:\Users\Administrator\Desktop\work\Cu-SaveManager-main\references\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TilemapModule">
      <HintPath>C:\Users\Administrator\Desktop\work\Cu-SaveManager-main\references\UnityEngine.TilemapModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.GridModule">
      <HintPath>C:\Users\Administrator\Desktop\work\Cu-SaveManager-main\references\UnityEngine.GridModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>C:\Users\Administrator\Desktop\work\Cu-SaveManager-main\references\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>C:\Users\Administrator\Desktop\work\Cu-SaveManager-main\references\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>C:\Users\Administrator\Desktop\work\Cu-SaveManager-main\references\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>